# CI on Windows via appveyor
# This file was based on Olivier Grisel's python-appveyor-demo

environment:

  matrix:
    - PYTHON: "C:\\Python34-conda64"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "64"

install:
  - Invoke-WebRequest "http://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe" -OutFile "$Home\miniconda3.exe"
  - .\miniconda3.exe /RegisterPython=1 /S /D="$Home\miniconda3" | Out-Null
  - $env:Path += ";$Home\miniconda3\;$Home\miniconda3\Scripts"
  - conda config --set ssl_verify false
  - conda env create python=3.5 -y
  - source activate phy
  - conda install -c kwikteam klustakwik2 -y
  - conda config --set ssl_verify true
  - pip install -r requirements-dev.txt
  - pip install -e .
build: false  # Not a C# project, build stuff at the test step instead.
test_script:
  # Run the project tests
  - py.test phy
