# CI on Windows via appveyor
# This file was based on Olivier Grisel's python-appveyor-demo

environment:
  matrix:
    - PYTHON: "C:\\Python34-conda64"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "64"
install:
  - ps: Start-FileDownload 'http://repo.continuum.io/miniconda/Miniconda-latest-Windows-x86_64.exe'
  - ps: .\Miniconda-latest-Windows-x86_64.exe /RegisterPython=1 /S /D="$Home\miniconda3" | Out-Null
  - ps: $env:Path += ";$Home\miniconda3\;$Home\miniconda3\Scripts"
  - ps: conda config --set ssl_verify false
  - ps: conda env create python=3.4
  - ps: activate phy
  - ps: conda install -c kwikteam klustakwik2 -y
  - ps: conda config --set ssl_verify true
  - ps: pip install -r requirements-dev.txt
  - ps: pip install -e .
build: false  # Not a C# project, build stuff at the test step instead.
test_script:
  # Run the project tests
  - py.test phy
