name: Install and Test with Pip

on:
  pull_request:
  push:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install test dependencies
        pip install -r requirements-dev.txt
        pip install git+https://github.com/cortex-lab/phy.git
    - name: Test apps
      run: |
        pytest phy/apps
    - name: Test with pytest utils
      run: |
        pytest phy/utils
    - name: Test with pytest cluster
      run: |
        pytest phy/cluster
